// src/components/avatarList.js

const avatars = [
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_1.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_2.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_3.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_4.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_5.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_6.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_7.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_8.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_9.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_10.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_11.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_12.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_13.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_14.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_15.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_16.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_17.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_18.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_19.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_20.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_21.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_22.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_23.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_24.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_25.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_26.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_27.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_28.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_29.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_30.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_31.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_32.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_33.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_34.png",
    "https://cdn.jsdelivr.net/gh/alohe/avatars/png/memo_35.png",
];

export default avatars;
